# Change these first
owner: Snigdha-OS
repo: snigdhaos-status
assignees:
  - eshanized
  - d3v1l0n
sites:
  - name: SNIGDHAOS-ORG
    url: https://snigdhaos.org
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-IO
    url: https://snigdha-os.github.io
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-PACKAGE_BROWSER
    url: https://snigdha-os.github.io/package-browser/
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-FORUM
    url: https://forum.snigdhaos.org
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  # - name: SNIGDHAOS-DOCS
  #   url: https://snigdhaos.org/documentation/
  #   icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-IODOCS
    url: https://snigdha-os.github.io/documentation/
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-CORE
    url: https://snigdha-os.github.io/snigdhaos-core/
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  - name: SNIGDHAOS-EXTRA
    url: https://snmirror.github.io/snigdhaos-extra/
    icon: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.snigdhaos.org
  baseUrl: /snigdhaos-status
  logoUrl: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  faviconSvg: https://raw.githubusercontent.com/Snigdha-OS/snigdhaos-assets/refs/heads/master/2024/svg/Snigdha%20OS%20Favicon.svg
  name: Snigdha OS Status
  introTitle: "Am I Running?"
  introMessage: Powered by Upptime
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://snigdhaos.org/

commitMessages:
  commitAuthorName: "Eshan Roy"
  commitAuthorEmail: "m.eshanized@gmail.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
